### ISSUE TITLE
Split ES nodes into master, data and client

### ISSUE THREAD

**Issue by pavolloffay** [RHsyseng/docker-rhel-elasticsearch#5]

**Comment by ruromero** [comment]
@pavolloffay I think you should be able to achieve so by using different configmaps. I haven't tried, though. e.g.
master-es-configmap
```
elasticsearch.yml: |
cluster:
  name: elasticsearch
network:
  host: 0.0.0.0
cloud:
  kubernetes:
    service: ${SERVICE}
    namespace: ${NAMESPACE}
discovery:
  zen.hosts_provider: kubernetes
  zen.minimum_master_nodes: "${NODE_QUORUM}"
node:
  master: true
  data: false
path:
  data: /elasticsearch/persistent/elasticsearch/data
  logs: /elasticsearch/logs
```
data-es-configmap
```
elasticsearch.yml: |
cluster:
  name: elasticsearch
network:
  host: 0.0.0.0
cloud:
  kubernetes:
    service: ${SERVICE}
    namespace: ${NAMESPACE}
discovery:
  zen.hosts_provider: kubernetes
  zen.minimum_master_nodes: "${NODE_QUORUM}"
node:
  master: false
  data: true
path:
  data: /elasticsearch/persistent/elasticsearch/data
  logs: /elasticsearch/logs
```
